version: '3' # docker-compose
services:
  centos:
    container_name: centos
    image: centos7 # customized image
    build: # as image doesn't exist
      context: centos7  # directory Dockerfile located, use the Dockerfile to build
    networks:
      - net # to allower communication  between services
  db_mysql:
    container_name: database
    image: mysql:5.7 
    environment:
      - "MYSQL_ROOT_PASSWORD=12345"
    volume:
      - "$PWD/db_mysql_data:/var/lib/mysql"   # host dir:container dir,  # present working directory(PWD) -> from container to local machine(right to left)
    networks:
      - net # # use 'net', we made 'networks' on the same level of services, within network
networks:
  net: